import type { NextPage } from 'next';
import Head from 'next/head';
import Booking from '../components/Booking';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Test hotel Disney</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/mickeyLogo.png" />
      </Head>

      <Booking />
     
    </div>
  )
}

export default Home
