import { Form, Formik } from 'formik';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useEffect } from 'react';
import { useDispatch } from 'react-redux';
import { number, object, string } from 'yup';
import { setDescription, setStep } from "../store/stepSlice";
import UserForm from '../components/Resume/UserForm';
import Basket from '../components/Resume/Basket';
import ResumeDate from '../components/Resume/ResumeDate';
import Router from 'next/router';

const Resume: NextPage = () => {
    const dispatch = useDispatch();

    const validationSchema = object({
      firstName: string().max(50).required('Veuillez entrer un prénom').matches(/^[aA-zZ\s]+$/, "Seul les lettres sont autorisées"),
      lastName: string().max(50).required('Veuillez entrer un nom de famille').matches(/^[aA-zZ\s]+$/, "Seul les lettres sont autorisées"),
      mail: string().email("Entrez une adresse mail valide").required('Veuillez entrer une adresse mail'),
      street: string().max(100).required('Veuillez entrez une rue'),
      country: number().min( 1, "Veuillez sélectionnez un pays").required(),
      city: string().max(50).required('Veuillez entrer une ville').matches(/^[aA-zZ\s]+$/, "Seul les lettres sont autorisées"),
      zipCode: string()
      .required("Veuillez entrez un code postal")
      .matches(/^[0-9]+$/, "Veuillez entrez un code postal valide")
      .min(5, "Veuillez entrez un code postal valide")
      .max(5, "Veuillez entrez un code postal valide"),
    });

    const initialValues = {
      firstName: "",
      lastName: "",
      mail: "",
      country: 0,
      street: "",
      zipCode: "",
      city: "",
  };

  useEffect(() => {
    dispatch(setStep(3));
    dispatch(setDescription('Confirmation du panier'))
  }, [])

      const handleSubmit = () => {
        Router.push('/final')
    };

  return (
    <div className='mx-16'>
      <Head>
        <title>Test hotel Disney</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/mickeyLogo.png" />
      </Head>

      <Formik
        initialValues={initialValues}
        validationSchema={validationSchema}
        onSubmit={() =>handleSubmit()}>
        {() => ( 
          <Form>
            <ResumeDate />
            <div className="grid grid-cols-2 gap-4 mt-4">
              <UserForm />
              <Basket />
            </div>
          </Form>
          )}
      </Formik>
    </div>
    
  )
}

export default Resume
