import type { NextPage } from 'next';
import Head from 'next/head';
import { useEffect } from 'react';
import { useDispatch } from 'react-redux';
import ShowsList from '../components/ShowsList';
import { setStep } from "../store/stepSlice";

const Shows: NextPage = () => {
    const dispatch = useDispatch();

    useEffect(() => {
        dispatch(setStep(2))
      }, [])

  return (
    <div>
      <Head>
        <title>Test hotel Disney</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/mickeyLogo.png" />
      </Head>
        <ShowsList />
    </div>
  )
}

export default Shows
